### ISSUE TITLE
Benchmarks for DDEs

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBenchmarks.jl#3]
We should start getting some benchmarks together for DDEs. There probably aren't many good ones with analytical solutions, so the `appxsol` stuff will have to be used on the simplest examples. Show the difference between constrained and unconstrained, the the difference that order makes in DDEs. Also see the difference between the OwrenZen optimized interpolant methods and the classic optimized RK methods to see if it really makes a difference.

@devmotion do you have any model equations to consider?

**Comment by devmotion** [comment]
In my master thesis I'm mostly working with the model (and some variants of it) in https://link.springer.com/article/10.1007%2Fs00216-014-8063-6. However, it contains a bunch of parameters, only one variable with delay, one variable that tends to oscillate betweeen positive and negative values although mathematically it has to be positive all the time, and some variables that have to be positive in the original model to ensure a real solution (there are some arbitrary real exponents). So I guess this might not be the best suited model for benchmarks ;)

However, in http://www.radford.edu/%7Ethompson/RP/dklag6.pdf which you posted in the issue about generic state-dependent delay handling the authors benchmark different versions of their program with three different models. The first two of them are state-dependent delay models (so not suited yet), but the third example, especially the integral-free version on p. 327, could be used. They had to run their program twice since after a certain time point D the equations change from an ODE to a DDE system but with DelayDiffEq we can compute the solution in one run.

**Comment by ChrisRackauckas** [comment]
>although mathematically it has to be positive all the time

Is this a numerical issue?

>So I guess this might not be the best suited model for benchmarks ;)

That sounds like a perfect benchmark. ROBER and VanDerPol became popular ODE benchmarks precisely because they could make a lot of stiff solvers fail. If this is such an equation, then it would nice to have a reference version as a benchmark and be able to track how well we do, and find out what we can do to improve it, or at least what kinds of options are required to handle it well.

**Comment by devmotion** [comment]
> Is this a numerical issue?

Maybe to some part, but I already could improve the results by setting element-wise absolute tolerances (the variables are on quite different scales). However, only with the additional effort of restricting the solution to positive values, as discussed in https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/issues/12, I could obtain quite good results.

> If this is such an equation, then it would nice to have a reference version as a benchmark and be able to track how well we do, and find out what we can do to improve it, or at least what kinds of options are required to handle it well.

I will reevaluate how well it performs since we changed the algorithm in mean time, so the plots shown in https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/issues/12 have changed probably.

**Comment by devmotion** [comment]
I just did some plots (without any benchmarking regarding time or memory) of the critical variable in my system. It is very small compared to the other four variables, so without element-wise absolut tolerances and without any other options I usually do not get a satisfying solution:

BS3
![figure_1_bs3](https://user-images.githubusercontent.com/26102/29098204-6d65bc26-7c9e-11e7-9724-f70de09e6438.png)

Tsit5
![figure_1_tsit5](https://user-images.githubusercontent.com/26102/29098220-84c5e148-7c9e-11e7-8fde-d31218a43c67.png)

DP5
![figure_1_dp5](https://user-images.githubusercontent.com/26102/29098226-8e809124-7c9e-11e7-96e2-cc0a97528992.png)

DP8
![figure_1_dp8](https://user-images.githubusercontent.com/26102/29098231-95f28f48-7c9e-11e7-8353-eb1f69464308.png)

OwrenZen3
![figure_1_owrenzen3](https://user-images.githubusercontent.com/26102/29098242-ac2aff8e-7c9e-11e7-9bcc-38128d07dea5.png)

OwrenZen4
![figure_1_owrenzen4](https://user-images.githubusercontent.com/26102/29098246-b71a2cda-7c9e-11e7-976d-898621e19eeb.png)

OwrenZen5
![figure_1_owrenzen](https://user-images.githubusercontent.com/26102/29098237-a3be5fee-7c9e-11e7-8a4b-2b6aa1114abc.png)

But wow, I'm impressed by the OwrenZen5 result 👍

**Comment by ChrisRackauckas** [comment]
>But wow, I'm impressed by the OwrenZen5 result

Yes, it controls the interpolation error the best. We should probably update the docs and suggest it as the Owren methods as the defaults for delay equations. Also try RK4 with its residual error estimator.

**Comment by devmotion** [comment]
And then I repeated these calculation with element-wise absolute tolerances. This improves all results (well, except of OwrenZen5) but still most of them still show some tiny oscillations.

BS3
![figure_1_bs3_autoabs](https://user-images.githubusercontent.com/26102/29098404-84f56f7a-7c9f-11e7-9a08-00700628a4f3.png)

Tsit5
![figure_1_tsit5_autoabs](https://user-images.githubusercontent.com/26102/29098424-99285638-7c9f-11e7-8cbf-f1e8b282b253.png)

DP5
![figure_1_dp5_autoabs](https://user-images.githubusercontent.com/26102/29098412-8e7cee06-7c9f-11e7-8082-44bf6e205020.png)

DP8
![figure_1_dp8_autoabs](https://user-images.githubusercontent.com/26102/29098433-a6b3eb5a-7c9f-11e7-9ad2-bd8bb13fda6f.png)

OwrenZen3
![figure_1_owrenzen3_autoabs](https://user-images.githubusercontent.com/26102/29098447-b304dd74-7c9f-11e7-8bca-72cb217b0713.png)

OwrenZen4
![figure_1_owrenzen4_autoabs](https://user-images.githubusercontent.com/26102/29098453-bb47eda0-7c9f-11e7-960b-9d71953d7610.png)

OwrenZen5
![figure_1_owrenzen5_autoabs](https://user-images.githubusercontent.com/26102/29098465-c6082872-7c9f-11e7-8ec5-19a5b486140b.png)

At first glance, all OwrenZen methods outperform the other algorithms here.

**Comment by ChrisRackauckas** [comment]
This is with no callback or isoutofdomain?

**Comment by devmotion** [comment]
Yes, exactly. With the callback I could get similar results for DP8 as for the OwrenZen methods shown above, but some of the other methods still showed these tiny fluctuations.

**Comment by ChrisRackauckas** [comment]
Part of it with `Tsit5` could be numerical issues with the interpolant. It's not using Horner's rule yet.

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/130

**Comment by devmotion** [comment]
I added RK4 to the plots above. With element-wise absolute tolerances it gives also a satisfying result.

**Comment by ChrisRackauckas** [comment]
Can we make this into a notebook?

**Comment by devmotion** [comment]
I'll transfer it to a notebook 👍 Which solver would you suggest for computing reference solutions?

In the references you posted I also discovered some other equations for benchmarking, so probably we can add some other notebooks as well.

**Comment by ChrisRackauckas** [comment]
>Which solver would you suggest for computing reference solutions?

Well, with lazy interpolants working `Vern9` at very low tolerances should be very accurate. But I think for this one the plots are a very good indicator of qualitative behavior in favor of the `OwrenZen` methods which should be showcased somewhere.

**Comment by ChrisRackauckas** [comment]
Cool. Future issues on this will be more specific.
